# Generated by Django 5.1 on 2025-08-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0002_petbackground_pettype_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mdq.petbackground'),
        ),
    ]
