# Generated by Django 5.1 on 2025-09-08 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mdq', '0002_petbackground_pettype_profile_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('difficulty', models.PositiveIntegerField(default=1)),
                ('time', models.IntegerField(default=10)),
                ('exp_reward', models.IntegerField(default=10)),
                ('credit_reward', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField(max_length=50)),
                ('uses', models.IntegerField(default=1)),
                ('icon', models.ImageField(upload_to='consumable/')),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('slot', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='cosmetic/')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='tasksicon/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='last_adventure',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credits',
        ),
        migrations.AlterField(
            model_name='pet',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mdq.petbackground'),
        ),
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClosetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.closet')),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.cosmetic')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdq.adventurelocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdq.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='tasksicon/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.consumable')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_url', models.URLField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('token_gp', models.DateTimeField(blank=True, default=None, null=True)),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='TasksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.customtasks')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.tasks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=1000)),
                ('pcredits', models.PositiveIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
