# Generated by Django 5.1 on 2025-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0007_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='task_lists', to='mdq.task'),
        ),
    ]
