# Generated by Django 5.1 on 2025-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0008_alter_taskslist_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
