# Generated by Django 5.1 on 2025-08-25 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pet_backgrounds/')),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=300)),
                ('pet_avatar', models.ImageField(upload_to='pets/')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pet', max_length=100)),
                ('exp', models.FloatField(default=0.0)),
                ('hp', models.PositiveIntegerField(default=20)),
                ('stamina', models.PositiveIntegerField(default=40)),
                ('bond', models.FloatField(default=0.0)),
                ('mood', models.IntegerField(default=50)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('last_fed', models.DateTimeField(blank=True, null=True)),
                ('last_adventure', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.petbackground')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.pettype')),
            ],
        ),
    ]
