# Generated by Django 5.1 on 2025-09-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0003_adventurelocation_consumable_cosmetic_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='custom_task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mdq.customtasks'),
        ),
        migrations.AlterField(
            model_name='taskslist',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mdq.tasks'),
        ),
    ]
