# Generated by Django 5.1 on 2025-09-08 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0004_alter_taskslist_custom_task_alter_taskslist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskslist',
            name='custom_task',
        ),
        migrations.RemoveField(
            model_name='taskslist',
            name='task',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='tasksicon/')),
                ('is_custom', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskslist',
            name='tasks',
            field=models.ManyToManyField(related_name='task_lists', to='mdq.task'),
        ),
        migrations.DeleteModel(
            name='CustomTasks',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
