# Generated by Django 5.1 on 2025-09-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0005_remove_taskslist_custom_task_remove_taskslist_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_custom',
            new_name='custom',
        ),
    ]
