# Generated by Django 5.1 on 2025-09-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0006_rename_is_custom_task_custom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
