# Generated by Django 5.1 on 2025-09-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdq', '0009_alter_task_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentadventure',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdq.adventurelocation'),
        ),
    ]
